CC = gcc
CFLAGS = -Wall

# Your C files (update this list)
SRC = longest_substring.c  test_longest_substring.c

# Output executable name
OUT = longest_substring

all:
	$(CC) $(CFLAGS) $(SRC) -o $(OUT)

clean:
	rm -f $(OUT)
